### PR TITLE
Update rails to 4.1.11 and other gem updates too

### PR DESCRIPTION
**Pull request by andrew**
Security updates mostly

### CODE REVIEW

**Comment by andrew** [comment]
Gah travis failure, will take a look later

**Comment by Floppy** [comment]
Thanks! That might just be because of encrypted test variables, I'll take a look.

**Comment by Floppy** [comment]
Ah, no, this is because the entire bundle caching system has changed and our build has bitrotted. I'll fix it on master and you can pull in a fix. :)

**Comment by andrew** [comment]
Rebased and rerunning the tests now

**Comment by andrew** [comment]
Had to get travis to run the migrations before running the test, got some actual failures which I'll investigate after work.

**Comment by Floppy** [comment]
Just pushing this into our repo to see if the fail is because travis is being odd.

**Comment by Floppy** [comment]
OK, only one actual real failure now, which is in the slash-encoding of the repository names. I think I've seen something like that before during a Rails upgrade... see https://travis-ci.org/theodi/forkbomb/builds/67379860.

**Comment by andrew** [comment]
This looks like the biscuit: https://github.com/rails/rails/issues/16058#issuecomment-48080131

**Comment by Floppy** [comment]
Looks likely!

**Pull request closed without merging**
